### ISSUE TITLE
Error message with VieVS GUI

### ISSUE THREAD

**Issue by sujataiitk** [TUW-VieVS/VLBI#5]
Writing 'vievs' in command line generates following error.
>> vievs
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click here. 
Index exceeds the number of array elements. Index must not exceed 0.

Error in saveParamFile (line 279)
        parameter.vie_mod.EOPfile=allEopFiles{get(handles.popupmenu_parameters_eop_aPriori_C04, 'Value')};

Error in vie_setup>vie_setup_OpeningFcn (line 495)
    saveParamFile(hObject, handles, defaultParamFilename)

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in vie_setup (line 149)
   gui_mainfcn(gui_State, varargin{:});

Error in vievs (line 81)
    vie_setup

>>vievs
Error using close
Unrecognized field name "data".

Error in close

Error in vievs (line 41)
close all;

Caused by:
    Error while evaluating figure CloseRequestFcn

**Comment by lch011600** [comment]
Hi! How did you solve this? Thanks!
